#**1.Use NumPY to generate an array of 25 random numbers sampled from a standard normal distribution.**


In [36]:
import numpy as np
numbers = np.random.normal(0,25,25)
numbers

array([  1.64497499,  -1.57128894,  13.9095979 , -10.8660113 ,
        10.3314724 , -35.58501345,  13.67925673, -10.25918328,
         9.33791569, -16.77605665,  58.29937397, -34.63454913,
       -34.90449119,  29.57127611,  -6.2538415 , -21.98747789,
        23.63012044,  22.97859272,  -3.76021149,  37.93254599,
        50.89550809,  -7.89789493,  -6.10497937,  16.85374313,
       -31.44888779])

#**2.Create an array of 20 linearly spaced points between 0 and 1.**


In [4]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

#**3.Declare a numpy array of values from 1 to 100 and make it into a 10*10 matrix.**

In [10]:
array1 = np.arange(1,101).reshape(10,10)
array1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

#**4.Using the previously defined matrix print rows of 1, 5, 6.**

In [14]:
print(array1[1])
print(array1[5])
print(array1[6])

[11 12 13 14 15 16 17 18 19 20]
[51 52 53 54 55 56 57 58 59 60]
[61 62 63 64 65 66 67 68 69 70]


**#5.Using the previously defined matrix print elements from 3rd row to 10th row.**

In [16]:
array1[2:10]

array([[ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

#**6.Using the previously defined matrix print all elements from 4th column to 8th column.**

In [18]:
array1[:,3:8]

array([[ 4,  5,  6,  7,  8],
       [14, 15, 16, 17, 18],
       [24, 25, 26, 27, 28],
       [34, 35, 36, 37, 38],
       [44, 45, 46, 47, 48],
       [54, 55, 56, 57, 58],
       [64, 65, 66, 67, 68],
       [74, 75, 76, 77, 78],
       [84, 85, 86, 87, 88],
       [94, 95, 96, 97, 98]])

#**7.Using the same matrix print values from 3rd row 2nd column to 5th row 8th column.**


In [20]:
array1[2:5,1:8]

array([[22, 23, 24, 25, 26, 27, 28],
       [32, 33, 34, 35, 36, 37, 38],
       [42, 43, 44, 45, 46, 47, 48]])

#**8.Write a code to generate a 1000 random numbers each in the range(0,1) such that the count of all random points like are almost same.**

In [23]:
array2 = np.random.randint(0,1,size = 1000)
array2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

#**9.Write the commands to get standard deviation, mean, mode, median for a given vector.**

In [30]:
from scipy import stats

vector = [2,56,23,234,98,2,21,34,2,90,19,2,11,1]

Mean = np.mean(vector)
Mode = stats.mode(vector)
Median = np.median(vector)
Standard_Deviation = np.std(vector)

print(Mean)
print(Mode)
print(Median)
print(Standard_Deviation)

42.5
ModeResult(mode=array([2]), count=array([4]))
20.0
61.48954614984799
